version: '{branch}-{build}'

build:
  verbosity: minimal

environment:
  matrix:
#  - BUILD: 'Debug'
#    CONFIG: debug
#    SHADOW_BUILD_DIR: $(APPVEYOR_BUILD_FOLDER)\build_windows_debug
  - BUILD: 'Release'
    CONFIG: installer
    SHADOW_BUILD_DIR: $(APPVEYOR_BUILD_FOLDER)\build_windows_install

install:
  - git submodule update --init --recursive
  - call "%ProgramFiles(x86)%\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x86
  - set PATH=C:\Qt\Tools\QtCreator\bin;C:\Qt\5.5\msvc2013\bin;%PATH%
  - mkdir %LOCALAPPDATA%\QtProject && copy test\qtlogging.ini %LOCALAPPDATA%\QtProject\
  - if "%CONFIG%" EQU "installer" ( cinst nsis.install -y -installArgs /D="%programfiles(x86)%\NSIS" )

build_script:
# temporary
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - mkdir %SHADOW_BUILD_DIR% && cd %SHADOW_BUILD_DIR% && C:\Qt\5.5\msvc2013\bin\qmake -r CONFIG-=debug_and_release CONFIG+=%CONFIG% CONFIG+=WarningsAsErrorsOn %APPVEYOR_BUILD_FOLDER%\qgroundcontrol.pro
  - cd %SHADOW_BUILD_DIR% && jom
  - if "%CONFIG%" EQU "installer" ( copy %SHADOW_BUILD_DIR%\release\qgroundcontrol-installer.exe %APPVEYOR_BUILD_FOLDER%\qgroundcontrol-installer.exe )
# Generate the source server information to embed in the PDB
  - '"C:\Program Files\Debugging Tools for Windows (x64)\srcsrv\srctool.exe" -r -u "%SHADOW_BUILD_DIR%\release\qgroundcontrol.pdb" | grep qgroundcontrol | grep -v moc_ | grep -v libs\\mavlink | grep -v build_windows_install | python %APPVEYOR_BUILD_FOLDER%\deploy\genPDBsrcsrv.py > %SHADOW_BUILD_DIR%\release\qgroundcontrol.pdb.srcsrv'
#write the source server info
  - '"C:\Program Files\Debugging Tools for Windows (x64)\srcsrv\pdbstr.exe" -w -i %SHADOW_BUILD_DIR%\release\qgroundcontrol.pdb.srcsrv -p:%SHADOW_BUILD_DIR%\release\qgroundcontrol.pdb -s:srcsrv'
# build the symbol / PE store
  - '"C:\Program Files\Debugging Tools for Windows (x64)\symstore.exe" add /compress /s symbols /f %SHADOW_BUILD_DIR%\release\qgroundcontrol.pdb /t qgroundcontrol'
  - '"C:\Program Files\Debugging Tools for Windows (x64)\symstore.exe" add /compress /s symbols /f %SHADOW_BUILD_DIR%\release\qgroundcontrol.exe /t qgroundcontrol'
  - ps: %APPVEYOR_BUILD_FOLDER%\deploy\lowercasify_symbolstore.ps1



test_script:
  - if "%CONFIG%" EQU "debug" ( %SHADOW_BUILD_DIR%\debug\qgroundcontrol --unittest )

artifacts:
  - path: qgroundcontrol-installer.exe
    name: qgcinstaller

  - path: symbols\**\*.*_
    name: symbols

deploy:
  - provider: S3
    access_key_id:
      secure: IGAojLMqokL+76DbdulmWDA3MTsxEBBi3ReVVSqTy9c=
    secret_access_key:
      secure: RiYqaR+3T2PMNz2j5ur8LCA6H/Zfd4jTX33CZE5iBxm+zaz4QLs25p0B7prpaoNN
    bucket: qgroundcontrol
    set_public: true
    folder: $(APPVEYOR_REPO_BRANCH)
    artifact: qgcinstaller
    on:
      CONFIG: installer
  - provider: GitHub
    auth_token:
      secure: dzWLqd0eTKjrAWC5LgqVnwLemmrNdddGA2ZZn/OthAP37mwCLkP2C1zil7ivmEE8
    artifact: qgcinstaller
    draft: false
    prerelease: false
    on:
      CONFIG: installer
      appveyor_repo_tag: true
